import {chromium} from '@playwright/test';
import bwip from 'bwip-js';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const qr=await bwip.toBuffer({bcid:'qrcode',text:'MULTISCAN-TEST-001',scale:5,padding:10});
const bar=await bwip.toBuffer({bcid:'code128',text:'ITEM-2048',scale:3,height:18,padding:10});
const server=createServer(async(req,res)=>{try{const p=req.url==='/'?'index.html':req.url.slice(1);const file=await readFile(new URL(`dist/${p}`,import.meta.url));res.setHeader('Content-Type',p.endsWith('.wasm')?'application/wasm':p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(file);}catch{res.writeHead(404);res.end();}}).listen(8091,'127.0.0.1');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:390,height:844}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({qr,bar})=>{
  document.modelContext={registerTool(tool){window.agentTool=tool;}};
  Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{
   const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=800;const c=canvas.getContext('2d');
   const images=await Promise.all([qr,bar].map(src=>new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.src=src;})));
   const draw=()=>{c.fillStyle='white';c.fillRect(0,0,1200,800);c.drawImage(images[0],100,100);c.drawImage(images[1],520,300);requestAnimationFrame(draw);};draw();const stream=canvas.captureStream(15),track=stream.getVideoTracks()[0];
   let torch=false;window.torchRequests=[];
   track.getCapabilities=()=>({torch:true});track.getSettings=()=>({torch});
   track.applyConstraints=async constraints=>{if(window.failTorch)throw new Error('Hardware failure');torch=constraints.advanced[0].torch;window.torchRequests.push(torch);};
   return stream;
  }});
  Object.defineProperty(navigator.mediaDevices,'enumerateDevices',{value:async()=>[{kind:'videoinput',deviceId:'test'}]});
 },{qr:`data:image/png;base64,${qr.toString('base64')}`,bar:`data:image/png;base64,${bar.toString('base64')}`});
 await page.goto('http://127.0.0.1:8091');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'/tmp/multiscan-mobile.png',fullPage:true});
 await page.click('#start');await page.waitForFunction(()=>document.querySelector('#count').textContent==='2',{},{timeout:30000});
 assert.match(await page.locator('#resultList').textContent(),/MULTISCAN-TEST-001/);assert.match(await page.locator('#resultList').textContent(),/ITEM-2048/);
 await page.waitForTimeout(800);assert.equal(await page.locator('#count').textContent(),'2');
 assert.equal(await page.locator('#visibleCount').textContent(),'2 in frame');
 assert.equal(await page.locator('.barcode-clip').count(),2);
 assert.equal(await page.locator('.barcode-clip').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0&&i.naturalHeight>0&&i.naturalWidth<=640&&i.naturalHeight<=640)),true);
 const croppedValues=await page.evaluate(async()=>{
  const worker=new Worker('/decoder.js',{type:'module'}),values=[];
  for(const img of document.querySelectorAll('.barcode-clip')){
   const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);
   const frame=c.getContext('2d').getImageData(0,0,c.width,c.height);
   const result=await new Promise(resolve=>{worker.onmessage=({data})=>resolve(data);worker.postMessage({id:1,frame});});values.push(...result.codes.map(code=>code.rawValue));
  }worker.terminate();return values.sort();
 });
 assert.deepEqual(croppedValues,['ITEM-2048','MULTISCAN-TEST-001']);
 await page.click('#torch');assert.equal(await page.locator('#torch').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#torch').textContent(),/Flash on/);
 await page.click('#torch');assert.equal(await page.locator('#torch').getAttribute('aria-pressed'),'false');assert.match(await page.locator('#torch').textContent(),/Flash off/);
 assert.deepEqual(await page.evaluate(()=>window.torchRequests),[true,false]);
 await page.evaluate(()=>window.failTorch=true);await page.click('#torch');assert.equal(await page.locator('#torch').getAttribute('aria-pressed'),'false');assert.match(await page.locator('#message').textContent(),/could not change/);
 await page.evaluate(()=>window.failTorch=false);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const result=await page.evaluate(()=>window.agentTool.execute({}));assert.equal(result.codes.length,2);assert.ok(result.codes.every(c=>c.hasClip&&!('clip' in c)));
 assert.equal(await page.evaluate(()=>{try{window.agentTool.execute({bad:true});return false;}catch{return true;}}),true);
 await page.click('#toggle');assert.equal(await page.locator('#status').textContent(),'Paused');
 await page.click('#toggle');await page.waitForFunction(()=>document.querySelector('#visibleCount').textContent==='2 in frame');
 await page.screenshot({path:'/tmp/multiscan-active.png',fullPage:true});
 await page.click('#stop');assert.equal(await page.locator('#status').textContent(),'Camera off');assert.equal(await page.locator('#count').textContent(),'2');
 assert.equal(await page.locator('.barcode-clip').count(),2);assert.equal(await page.locator('#torch').isDisabled(),true);
 await page.click('#clear');assert.equal(await page.locator('.barcode-clip').count(),0);assert.equal(await page.locator('#count').textContent(),'0');
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/multiscan-desktop.png',fullPage:true});
 const imageData=await page.evaluate(async({qr,bar})=>{
  const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=800;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1200,800);
  const imgs=await Promise.all([qr,bar].map(async src=>{const img=new Image();img.src=src;await img.decode();return img;}));ctx.drawImage(imgs[0],100,100);ctx.drawImage(imgs[1],520,300);return canvas.toDataURL('image/png').split(',')[1];
 },{qr:`data:image/png;base64,${qr.toString('base64')}`,bar:`data:image/png;base64,${bar.toString('base64')}`});
 const file={name:'multiple-barcodes.png',mimeType:'image/png',buffer:Buffer.from(imageData,'base64')};
 await page.locator('#imageFile').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#status').textContent==='Image scanned');
 assert.equal(await page.locator('#count').textContent(),'2');assert.equal(await page.locator('.barcode-clip').count(),2);assert.equal(await page.locator('#visibleCount').textContent(),'2 in image');assert.equal(await page.locator('#uploadedImage').isVisible(),true);
 await page.locator('#imageFile').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#status').textContent==='Image scanned');assert.equal(await page.locator('#count').textContent(),'2');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/multiscan-upload.png',fullPage:true});
 await page.click('#cameraMode');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Live');assert.equal(await page.locator('#uploadedImage').isVisible(),false);
 await page.locator('#imageFile').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#status').textContent==='Image scanned');assert.equal(await page.evaluate(()=>document.querySelector('#video').srcObject),null);
 const blank=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=300;c.height=300;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,300,300);return c.toDataURL('image/png').split(',')[1];});
 await page.locator('#imageFile').setInputFiles({name:'blank.png',mimeType:'image/png',buffer:Buffer.from(blank,'base64')});await page.waitForFunction(()=>document.querySelector('#message').textContent.startsWith('No barcodes found'));assert.equal(await page.locator('#count').textContent(),'2');
 await page.locator('#imageFile').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('not a real image')});await page.waitForFunction(()=>document.querySelector('#message').textContent.startsWith('Could not read'));assert.equal(await page.locator('#upload').isEnabled(),true);assert.equal(await page.locator('#count').textContent(),'2');
 const dense=await bwip.toBuffer({bcid:'code128',text:'DENSE-TEST-000123456789',scale:2,height:5,padding:15,backgroundcolor:'FFFFFF'});
 const retail=await bwip.toBuffer({bcid:'ean13',text:'9521234567899',scale:4,height:28,padding:15,backgroundcolor:'FFFFFF'});
 const labelData=await page.evaluate(async({dense,retail})=>{
  const images=await Promise.all([retail,dense].map(async src=>{const i=new Image();i.src=src;await i.decode();return i;}));
  const c=document.createElement('canvas');c.width=1600;c.height=1600;const ctx=c.getContext('2d');ctx.fillStyle='#a8aca2';ctx.fillRect(0,0,1600,1600);
  ctx.save();ctx.translate(300,750);ctx.rotate(-Math.PI/180);ctx.globalAlpha=.7;ctx.filter='blur(0.6px)';ctx.drawImage(images[0],0,0);ctx.drawImage(images[1],0,400);ctx.restore();
  ctx.fillStyle='#303030';ctx.fillRect(280,1100,1050,3);ctx.fillRect(280,1245,1050,3);return c.toDataURL('image/jpeg',.8).split(',')[1];
 },{dense:`data:image/png;base64,${dense.toString('base64')}`,retail:`data:image/png;base64,${retail.toString('base64')}`});
 await page.click('#clear');
 await page.locator('#imageFile').setInputFiles({name:'dense-stacked-label.jpg',mimeType:'image/jpeg',buffer:Buffer.from(labelData,'base64')});
 await page.waitForFunction(()=>document.querySelector('#status').textContent==='Image scanned',{},{timeout:30000});
 assert.equal(await page.locator('#count').textContent(),'2');assert.match(await page.locator('#resultList').textContent(),/DENSE-TEST-000123456789/);assert.match(await page.locator('#resultList').textContent(),/9521234567899/);
 assert.equal(await page.locator('.barcode-clip').count(),2);
 console.log('PASS: dense short barcode below a retail barcode in a tilted, blurred, low-contrast JPEG label; both values and crops recovered.');
 console.log('PASS: multi-barcode image upload, preview, clips, deduplication, reselecting same file, mobile layout, camera/image switching, blank image and corrupt file handling.');
 const denied=await browser.newPage();await denied.addInitScript(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{throw new DOMException('Denied','NotAllowedError');}}));
 await denied.goto('http://127.0.0.1:8091');await denied.click('#start');await denied.waitForFunction(()=>document.querySelector('#message').textContent.includes('denied'));
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: cropped images decode to matching results, flash on/off and hardware failure, clips retained on stop and removed on clear; actual QR + Code 128 decoding, multiple outlines, deduplication, pause/resume, stop, clear, mobile layout, permission error, WebMCP read and validation.');
}finally{await browser.close();server.close();}
